fix

diff --git a/.github/actions/promote-to-stable/action.yml b/.github/actions/promote-to-stable/action.yml
--- a/.github/actions/promote-to-stable/action.yml
+++ b/.github/actions/promote-to-stable/action.yml
@@ -67,16 +67,25 @@ runs:
         echo "[DEBUG] - Distrib: ${{ inputs.distrib }}"
         echo "[DEBUG] - Distrib: ${{ inputs.module }}"
 
+        if [ "${{ inputs.distrib }}" == "bullseye" ]; then
+          DISTRIB_SUFFIX="+deb11u1"
+        elif [ "${{ inputs.distrib }}" == "bookworm" ]; then
+          DISTRIB_SUFFIX="+deb12u1"
+        else
+          echo "::error::Distrib ${{ inputs.distrib }} not supported for promote"
+          exit 1
+        fi
+
         echo "[DEBUG] - Get path of testing DEB packages to promote to stable."
-        SRC_PATHS=$(jf rt search --include-dirs apt-plugins-testing/pool/${{ inputs.module }}/*${{ inputs.distrib }}*.deb | jq -r '.[].path')
+        SRC_PATHS=$(jf rt search --include-dirs apt-plugins-testing/pool/${{ inputs.module }}/*$DISTRIB_SUFFIX*.deb | jq -r '.[].path')
 
         if [[ ${SRC_PATHS[@]} ]]; then
           for SRC_PATH in ${SRC_PATHS[@]}; do
             echo "[DEBUG] - Source path found: $SRC_PATH"
           done
         else
-          echo "[DEBUG] - No source path found."
-          continue
+          echo "::warning::No packages to promote for ${{ inputs.distrib }}."
+          exit 0
         fi
 
         echo "[DEBUG] - Build target path."
@@ -95,5 +104,4 @@ runs:
           jf rt upload "$ARTIFACT_DL" "$TARGET_PATH" --deb "${{ inputs.distrib }}/main/$ARCH"
         done
         rm -f *.deb
-
       shell: bash
