enh(ci): move all deliveries to artifactory (#4687)
* move all deliveries to artifactory
* do not delivery nrpe service configuration
Refs: MON-22360

diff --git a/.github/actions/rpm-delivery-legacy/action.yml b/.github/actions/rpm-delivery-legacy/action.yml
--- a/.github/actions/rpm-delivery-legacy/action.yml
+++ b/.github/actions/rpm-delivery-legacy/action.yml
@@ -13,23 +13,11 @@ inputs:
   cache_key:
     description: "The cached package key"
     required: true
-  yum_repo_url:
-    description: "The legacy yum repo url"
-    required: true
-  update_repo_path:
-    description: "The update repo script path"
-    required: true
-  cloudfront_id:
-    description: "The cloudfront ID for repo url"
-    required: true
-  yum_repo_address:
-    description: "The legacy yum repo address"
-    required: true
-  yum_repo_key:
-    description: "The repo key"
-    required: true
   stability:
     description: "The package stability (stable, testing, unstable)"
+    required: true
+  artifactory_token:
+    description: "token for artifactory"
     required: true
 
 runs:
@@ -42,56 +30,46 @@ runs:
         key: ${{ inputs.cache_key }}
         fail-on-cache-miss: true
 
-    - name: Setup awscli
-      run: |
-        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-        sudo unzip -q awscliv2.zip
-        sudo ./aws/install
-      shell: bash
+    - uses: jfrog/setup-jfrog-cli@v3
+      env:
+        JF_URL: https://centreon.jfrog.io
+        JF_ACCESS_TOKEN: ${{ inputs.artifactory_token }}
 
-    - name: Publish RPMs to standard repositories
+    - name: Publish RPMs to standard repository
       run: |
         FILES="*.rpm"
 
-        REPOTYPE="${{ inputs.stability }}"
-        PROJECT_PATH="standard"
-        DISTRIB="${{ inputs.distrib }}"
-        ARCH="noarch"
+        echo "[DEBUG] - Distrib: ${{ inputs.distrib }}"
 
-        eval `ssh-agent`
-        ssh-add - <<< "${{ inputs.yum_repo_key }}"
-
-        echo "Delivering to ${{ inputs.major_version }} $REPOTYPE"
-
-        if [ "$REPOTYPE" == "stable" ]; then
-          TARGET="/srv/centreon-yum/yum.centreon.com/$PROJECT_PATH/${{ inputs.major_version }}/$DISTRIB/$REPOTYPE/$ARCH/RPMS"
-        else
-          TARGET="/srv/centreon-yum/yum.centreon.com/$PROJECT_PATH/${{ inputs.major_version }}/$DISTRIB/$REPOTYPE/$ARCH/${{ inputs.module_name }}"
-          PROJECT_LOCATION="/srv/centreon-yum/yum.centreon.com/$PROJECT_PATH/${{ inputs.major_version }}/$DISTRIB/$REPOTYPE/$ARCH/${{ inputs.module_name }}"
+        if [ -z "${{ inputs.module_name }}" ]; then
+          echo "::error::Module name is required"
+          exit 1
         fi
 
-        echo "[DEBUG] - Target : $TARGET"
-        echo "[DEBUG] - PROJECT_LOCATION : $PROJECT_LOCATION"
+        if [ -z "${{ inputs.distrib }}" ]; then
+          echo "::error::Distrib is required"
+          exit 1
+        fi
 
-        ssh -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" mkdir -p "$TARGET"
-        scp -o StrictHostKeyChecking=no ./*.rpm "${{ inputs.yum_repo_address }}:$TARGET"
+        mkdir noarch x86_64
 
-        # Update repository metadata
-        METADATAS="/srv/centreon-yum/yum.centreon.com/$PROJECT_PATH/${{ inputs.major_version }}/$DISTRIB/$REPOTYPE/$ARCH"
-        sleep $((RANDOM % 120)) # wait random time to avoid simultaneous createrepo
-        ssh -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" "sh "${{ inputs.update_repo_path }}" $METADATAS" 2>&-
+        for FILE in $FILES; do
+          echo "[DEBUG] - File: $FILE"
 
-        # Invalidate cloudfront cache
-        ID="${{ inputs.cloudfront_id }}"
-        PATHS="/$PROJECT_PATH/${{ inputs.major_version }}/$DISTRIB/$REPOTYPE/$ARCH/*"
-        ITERATIONS=1
+          ARCH=$(echo $FILE | grep -oP '(x86_64|noarch)')
 
-        until aws cloudfront create-invalidation --distribution-id "$ID" --paths "$PATHS"; do
-          if [ ${ITERATIONS} -eq 10 ]; then
-            return 0
+          echo "[DEBUG] - Arch: $ARCH"
+
+          cp "$FILE" "$ARCH"
+        done
+
+        for ARCH in "noarch" "x86_64"; do
+          if [ "$(ls -A $ARCH)" ]; then
+            if [ "${{ inputs.stability }}" == "stable" ]; then
+              jf rt upload "$ARCH/*.rpm" "rpm-standard/${{ inputs.major_version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH/RPMS/${{ inputs.module_name }}/" --flat
+            else
+              jf rt upload "$ARCH/*.rpm" "rpm-standard/${{ inputs.major_version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH/${{ inputs.module_name }}/" --flat
+            fi
           fi
-          echo "couldn't invalidate cache, AWS quota might have been reached, retrying in 30 seconds..."
-          sleep 30s
-          ITERATIONS=$((ITERATIONS+1))
         done
       shell: bash
