fix

diff --git a/.github/actions/deb-delivery/action.yml b/.github/actions/deb-delivery/action.yml
--- a/.github/actions/deb-delivery/action.yml
+++ b/.github/actions/deb-delivery/action.yml
@@ -41,7 +41,7 @@ runs:
 
           for FILE in *.deb; do
             sleep 2
-            curl --connect-timeout 10 --retry 2 --retry-max-time 30 --retry-all-errors --fail --silent --show-error -u '${{ inputs.nexus_username }}':'${{ inputs.nexus_password }}' -H 'Content-Type: multipart/form-data' --data-binary "@./$FILE" https://apt.centreon.com/repository/$MAJOR$FOLDER_SUFFIX/ || echo "::error::Fail to deliver $FILE $MAJOR"
+            curl --connect-timeout 10 --retry 2 --retry-max-time 30 --fail --silent --show-error -u '${{ inputs.nexus_username }}':'${{ inputs.nexus_password }}' -H 'Content-Type: multipart/form-data' --data-binary "@./$FILE" https://apt.centreon.com/repository/$MAJOR$FOLDER_SUFFIX/ || echo "::error::Fail to deliver $FILE $MAJOR"
           done
         done
       shell: bash
