trigger delivery

diff --git a/.github/actions/deb-delivery/action.yml b/.github/actions/deb-delivery/action.yml
--- a/.github/actions/deb-delivery/action.yml
+++ b/.github/actions/deb-delivery/action.yml
@@ -29,19 +29,9 @@ runs:
         path: ./*.deb
         key: ${{ inputs.cache_key }}
 
-    - uses: jfrog/setup-jfrog-cli@v3
-      env:
-        JF_URL: https://centreon.jfrog.io
-        JF_ACCESS_TOKEN: ${{ inputs.artifactory_token }}
-
-    - name: Publish DEBs to artifactory
-      run: |
-        jf rt upload "*.deb" "apt-plugins-${{ inputs.stability }}/pool/" --deb "${{ inputs.distrib }}/main/all"
-      shell: bash
-
     - name: Publish DEBs to Nexus
       run: |
-        for MAJOR in "22.04" "22.10"; do
+        for MAJOR in "22.10"; do
           echo "Delivering to $MAJOR ${{ inputs.stability }}"
 
           FOLDER_SUFFIX="-${{ inputs.stability }}"
@@ -49,6 +39,9 @@ runs:
             FOLDER_SUFFIX=""
           fi
 
-          find -name "*.deb" -print0 | xargs -0 -t -I % -P 2 sh -c "curl --connect-timeout 10 --retry 2 --retry-max-time 30 --fail --silent --show-error -u '${{ inputs.nexus_username }}':'${{ inputs.nexus_password }}' -H 'Content-Type: multipart/form-data' --data-binary '@%' https://apt.centreon.com/repository/$MAJOR$FOLDER_SUFFIX/ >/dev/null || exit 255" || break
+          for FILE in *.deb; do
+            sleep 2
+            curl --connect-timeout 10 --retry 2 --retry-max-time 30 --retry-all-errors --fail --silent --show-error -u '${{ inputs.nexus_username }}':'${{ inputs.nexus_password }}' -H 'Content-Type: multipart/form-data' --data-binary "@./$FILE" https://apt.centreon.com/repository/$MAJOR$FOLDER_SUFFIX/ || echo "::error::Fail to deliver $FILE $MAJOR"
+          done
         done
       shell: bash
