add failsafes

diff --git a/.github/workflows/get-environment.yml b/.github/workflows/get-environment.yml
--- a/.github/workflows/get-environment.yml
+++ b/.github/workflows/get-environment.yml
@@ -250,11 +250,14 @@ jobs:
       - name: "Get release: 1 for testing / stable, <date>.<commit_sha> for others"
         id: get_release
         run: |
-          RELEASE=$(echo ${{ github.ref_name }} | cut -d "-" -f2)-1
-
-          if [[ $(#RELEASE) != 10 || ${RELEASE::2} != 20 || ! ${RELEASE:4: -4} =~ ^0[1-9]$|1[0-2]$ ]]; then
-            echo "invalid release name"
-            exit 1
+          if [[ ${{ steps.get_stability.outputs.stability }} == "testing" || ${{ steps.get_stability.outputs.stability }} == "stable" ]]; then
+            RELEASE=$(echo ${{ github.ref_name }} | cut -d "-" -f2)-1
+            if [[ $(#RELEASE) != 10 || ${RELEASE::2} != 20 || ! ${RELEASE:4: -4} =~ ^0[1-9]$|1[0-2]$ ]]; then
+              echo "invalid release name"
+              exit 1
+            fi
+          else
+            RELEASE=$(date '+%H%M%S')
           fi
 
           echo "release=$RELEASE" >> $GITHUB_OUTPUT
