Move CPAN libs tests in an action, and add fixes for el8 / el9

diff --git a/.github/workflows/perl-cpan-libraries.yml b/.github/workflows/perl-cpan-libraries.yml
--- a/.github/workflows/perl-cpan-libraries.yml
+++ b/.github/workflows/perl-cpan-libraries.yml
@@ -159,7 +159,28 @@ jobs:
 
     steps:
       - if: ${{ contains(matrix.build_distribs, matrix.distrib) }}
-        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
+
+      - if: ${{ contains(matrix.build_distribs, matrix.distrib) }}
+        name: Get package infos
+        id: package-infos
+        run: |
+          cpan_info=$(cpanm --info ${{ matrix.name }})
+          if [ -z "${{ matrix.version }}" ]; then
+            CPAN_PACKAGE_VERSION=$(echo $cpan_info | sed 's/\.tar\.gz$//' | sed 's/.*\-//' | sed 's/v//')
+            if [[ ! $CPAN_PACKAGE_VERSION =~ ^[0-9]+\.[0-9]+ ]]; then
+              echo "::error::Invalid version number: ${CPAN_PACKAGE_VERSION}"
+              exit 1
+            fi
+            PACKAGE_VERSION="${CPAN_PACKAGE_VERSION}"
+          else
+            PACKAGE_VERSION="${{ matrix.version }}"
+          fi
+          echo "package_version=$(echo $PACKAGE_VERSION)" >> $GITHUB_OUTPUT
+          CPAN_PACKAGE_NAME=$(echo $cpan_info | sed 's/.*\///g' | sed 's/-[0-9\.]*\.tar\.gz//g')
+          PACKAGE_NAME="perl-$CPAN_PACKAGE_NAME"
+          echo "package_name=$(echo $PACKAGE_NAME)" >> $GITHUB_OUTPUT
+        shell: bash
 
       - if: ${{ contains(matrix.build_distribs, matrix.distrib) }}
         name: Check if package already exists
@@ -168,8 +189,8 @@ jobs:
           package_info=$(dnf provides 'perl(${{ matrix.name }})' 2>&1 | tr '[:upper:]' '[:lower:]' || true)
           do_not_build="false"
           if [[ ! $package_info =~ "no matches found" ]]; then
-            package_version=$(echo $package_info | grep -oP 'perl\(${{ matrix.name }}\) = \K[0-9]+\.[0-9]+')
-            if [[ -z "${{ matrix.version }}" || "$package_version" == "${{ matrix.version }}" ]]; then
+            package_version=$(echo $package_info | grep -oP "perl\($(echo ${{ matrix.name }} | tr '[:upper:]' '[:lower:]')\) = \K[0-9]+\.[0-9]+")
+            if [[ "$package_version" == "${{ steps.package-infos.outputs.package_version }}" ]]; then
               echo "::warning::Package ${{ matrix.name }} already exists in the official ${{ matrix.distrib }} repository with the same version."
               do_not_build="true"
             else
@@ -182,11 +203,7 @@ jobs:
 
       - if: ${{ steps.check-package-existence.outputs.do_not_build == 'false' && contains(matrix.build_distribs, matrix.distrib) && matrix.spec_file == '' }}
         run: |
-          if [ -z "${{ matrix.version }}" ]; then
-            PACKAGE_VERSION=""
-          else
-            PACKAGE_VERSION=" -v ${{ matrix.version }}"
-          fi
+          PACKAGE_VERSION=" -v ${{ steps.package-infos.outputs.package_version }}"
 
           if [ -z "${{ matrix.rpm_dependencies }}" ]; then
             PACKAGE_DEPENDENCIES=""
@@ -215,6 +232,7 @@ jobs:
           export SYBASE="/usr"
 
           temp_file=$(mktemp)
+          echo "default.local" | tee /etc/mailname
           created_package=$(fpm -s cpan -t ${{ matrix.package_extension }} --rpm-dist ${{ matrix.distrib }} --verbose --cpan-verbose --no-cpan-test$PACKAGE_DEPENDENCIES$PACKAGE_PROVIDES$PACKAGE_VERSION ${{ matrix.name }} | tee "$temp_file" | grep "Created package" | grep -oP '(?<=:path=>").*?(?=")')
           # Check package name
           if [ -z "$created_package" ]; then
@@ -298,7 +316,7 @@ jobs:
       - run: apt-get install -y zstd
         shell: bash
 
-      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
 
       - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
         with:
@@ -438,7 +456,7 @@ jobs:
 
     steps:
       - if: ${{ contains(matrix.build_names, matrix.build_name) }}
-        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
 
       - if: ${{ contains(matrix.build_names, matrix.build_name) }}
         name: Parse distrib name
@@ -509,6 +527,7 @@ jobs:
           fi
 
           temp_file=$(mktemp)
+          echo "default.local" | tee /etc/mailname
           created_package=$(fpm -s cpan -t ${{ matrix.package_extension }} --deb-dist ${{ matrix.distrib }} --iteration ${{ steps.parse-distrib.outputs.package_distrib_name }} --verbose --cpan-verbose --no-cpan-test$PACKAGE_DEPENDENCIES -v ${{ steps.package-infos.outputs.package_version }} ${{ matrix.name }} | tee "$temp_file" | grep "Created package" | grep -oP '(?<=:path=>").*?(?=")')  || { echo "Error: fpm command failed"; exit 1; }
           # Check package name
           if [ -z "$created_package" ]; then
@@ -529,7 +548,7 @@ jobs:
           created_package=$(DEB_BUILD_OPTIONS="nocheck nodocs notest" dh-make-perl make --dist ${{ matrix.distrib }} --build --version ${{ steps.package-infos.outputs.package_version }}${{ steps.parse-distrib.outputs.package_distrib_separator }}${{ steps.parse-distrib.outputs.package_distrib_name }} --cpan ${{ matrix.name }} | tee "$temp_file" | grep "building package" | grep -oP "(?<=in '..\/).*.deb(?=')") || { echo "Error: dh-make-perl command failed"; exit 1; }
           # Check package name
           if [ -z "$created_package" ]; then
-            echo "Error: fpm command failed"
+            echo "Error: dh-make-perl command failed"
             exit 1
           fi
           # Check deb
@@ -641,114 +660,15 @@ jobs:
 
     name: Test perl CPAN libs packages on ${{ matrix.package_extension }} ${{ matrix.distrib }} ${{ matrix.arch }}
     steps:
-      - if: ${{ matrix.package_extension == 'rpm' }}
-        name: Install zstd, perl and Centreon repositories
-        run: |
-          dnf install -y zstd perl epel-release 'dnf-command(config-manager)'
-          dnf config-manager --set-enabled powertools || true # alma 8
-          dnf config-manager --set-enabled crb || true # alma 9
-          # Import Centreon GPG key
-          GPG_KEY_URL="https://yum-gpg.centreon.com/RPM-GPG-KEY-CES"
-          curl -sSL $GPG_KEY_URL -o RPM-GPG-KEY-CES
-          rpm --import RPM-GPG-KEY-CES
-        shell: bash
 
-      - if: ${{ matrix.package_extension == 'deb' }}
-        name: Install zstd, perl and Centreon repositories
-        run: |
-          export DEBIAN_FRONTEND=noninteractive
-          apt-get update
-          apt-get install -y zstd perl wget gpg apt-utils procps
-          wget -O- https://apt-key.centreon.com | gpg --dearmor | tee /etc/apt/trusted.gpg.d/centreon.gpg > /dev/null 2>&1
-          # Avoid apt to clean packages cache directory
-          rm -f /etc/apt/apt.conf.d/docker-clean
-          apt-get update
-        shell: bash
+      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
 
-      - name: Restore packages from cache
-        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
+      - name: Test packaged libs
+        uses: ./.github/actions/test-cpan-libs
         with:
-          path: ./*.${{ matrix.package_extension }}
-          key: ${{ github.sha }}-${{ github.run_id }}-${{ matrix.package_extension }}-${{ matrix.distrib }}
-          fail-on-cache-miss: true
-
-      - if: ${{ matrix.package_extension == 'rpm' }}
-        name: Install packages
-        run: |
-          error_log="install_error_${{ matrix.distrib }}_${{ matrix.arch }}.log"
-          for package in ./*.rpm; do
-            echo "Installing package: $package"
-            # List dependencies, and remove version and comparison operators
-            dependencies=$(rpm -qpR $package | sed 's/ [0-9.-]*\(\s\|$\)/ /g' | sed 's/ [<>!=]*\(\s\|$\)/ /g')
-            for dependency in $dependencies; do
-              # Skip non-perl dependencies
-              if [[ $dependency != perl* ]]; then
-                continue
-              else
-                echo "Check dependency: $dependency"
-                # Update the dependency name to match the package name
-                dependency=$(echo $dependency | sed 's/(/-/g' | sed 's/)//g' | sed 's/::/-/g')
-              fi
-              # If the dependency has been built in the same workflow, install it
-              if [[ -n $(find . -maxdepth 1 -regex "\.\/$dependency-[0-9v].*\.rpm") ]]; then
-                echo "Installing dependency: $dependency"
-                error_output=$(dnf install -y ./$dependency*.rpm 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of the dependency $dependency" >> $error_log; true; }
-              fi
-            done
-            # Install package, then uninstall it with all his dependencies
-            echo "Package installation..."
-            error_output=$(dnf install -y $package 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of the package $package" >> $error_log; true; }
-            echo "Package installation done."
-            echo "Package uninstallation..."
-            error_output=$(dnf autoremove --setopt=keepcache=True -y $(echo $package | sed 's/_[0-9].*\.rpm//' | sed 's/.\///') 2>&1) || { echo "$error_output" >> $error_log; echo "Error during autoremove of the package $package" >> $error_log; true; }
-            echo "Package uninstallation done."
-          done
-          # If the file error_log exists and is not empty, the workflow is in error
-          if [[ -s $error_log ]]; then
-              cat $error_log
-              exit 1
-          fi
-        shell: bash
-
-      - if: ${{ matrix.package_extension == 'deb' }}
-        name: Install packages
-        run: |
-          error_log="install_error_${{ matrix.distrib }}_${{ matrix.arch }}.log"
-          for package in ./*.deb; do
-            # If the debian package name ends with amd64 or arm64, we only install it if the tested architecture is the same, otherwise we skip it
-            if [[ $package == *amd64.deb && ${{ matrix.arch }} != "amd64" || $package == *arm64.deb && ${{ matrix.arch }} != "arm64" ]]; then
-              continue
-            fi
-            echo "Installing package: $package"
-            # List dependencies
-            dependencies=$(dpkg-deb -I $package | grep Depends | sed 's/Depends: //' | sed 's/,//g' | sed 's/(\(.*\)//g') || { echo "$error_output" >> $error_log; echo "Error while listing dependencies of the package $package" >> $error_log; true; }
-            for dependency in $dependencies; do
-              # If the dependency exists in the Debian repository, don't check the local dependencies
-              dependency_info=$(apt-cache policy $dependency)
-              if [[ -n $dependency_info ]]; then
-                echo "Dependency $dependency exists in debian repository."
-              else
-                # If the dependency has been built in the same workflow, install it
-                for dependency_package in $(find . -maxdepth 1 -regex "\.\/${dependency}_[0-9].*all\.deb" -o -regex "\.\/${dependency}_[0-9].*${{ matrix.arch }}\.deb"); do
-                  echo "Installing dependency: $dependency_package"
-                  error_output=$(apt-get install -y ./$dependency_package 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of the dependency $dependency" >> $error_log; true; }
-                done
-              fi
-            done
-            # Install package, then uninstall it with all his dependencies
-            echo "Package installation..."
-            error_output=$(apt-get install -y $package 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of the package $package" >> $error_log; true; }
-            echo "Package installation done."
-            echo "Package uninstallation..."
-            error_output=$(apt-get autoremove -y --purge $(echo $package | sed 's/_[0-9].*\.deb//' | sed 's/.\///') 2>&1) || { echo "$error_output" >> $error_log; echo "Error during autoremove of the package $package" >> $error_log; true; }
-            echo "Package uninstallation done."
-          done
-          # If the file error_log exists and is not empty, the workflow is in error
-          if [[ -s $error_log ]]; then
-              cat $error_log
-              exit 1
-          fi
-        shell: bash
+          package_extension: ${{ matrix.package_extension }}
+          distrib: ${{ matrix.distrib }}
+          arch: ${{ matrix.arch }}
 
       - name: Upload error log
         if: failure()
