fix dependencies installation

diff --git a/.github/workflows/perl-cpan-libraries.yml b/.github/workflows/perl-cpan-libraries.yml
--- a/.github/workflows/perl-cpan-libraries.yml
+++ b/.github/workflows/perl-cpan-libraries.yml
@@ -92,6 +92,7 @@ jobs:
           - rpm_provides: ""
           - version: ""
           - spec_file: ""
+          - no-auto-depends: false
           - distrib: el8
             package_extension: rpm
             image: packaging-plugins-alma8
@@ -135,7 +136,6 @@ jobs:
           - name: "ZMQ::LibZMQ4"
             version: "0.01"
             rpm_dependencies: "zeromq"
-
 
     name: package ${{ matrix.distrib }} ${{ matrix.name }}
     container:
@@ -572,8 +572,12 @@ jobs:
           dnf install -y zstd perl epel-release 'dnf-command(config-manager)'
           dnf config-manager --set-enabled powertools || true # alma 8
           dnf config-manager --set-enabled crb || true # alma 9
+          # Import Centreon GPG key
+          GPG_KEY_URL="https://yum-gpg.centreon.com/RPM-GPG-KEY-CES"
+          curl -sSL $GPG_KEY_URL -o RPM-GPG-KEY-CES
+          rpm --import RPM-GPG-KEY-CES
           # Add Centreon plugins repositories
-          echo -e '[centreon-plugins-stable]\nname=centreon plugins stable x86_64\nbaseurl=https://packages.centreon.com/rpm-plugins/${{ matrix.distrib }}/stable/x86_64\nenabled=1\ngpgcheck=1\ngpgkey=https://yum-gpg.centreon.com/RPM-GPG-KEY-CES\n[centreon-plugins-stable-noarch]\nname=centreon plugins stable noarch\nbaseurl=https://packages.centreon.com/rpm-plugins/${{ matrix.distrib }}/stable/noarch\nenabled=1\ngpgcheck=1\ngpgkey=https://yum-gpg.centreon.com/RPM-GPG-KEY-CES\n' >> /etc/yum.repos.d/centreon-plugins.repo
+          # echo -e '[centreon-plugins-stable]\nname=centreon plugins stable x86_64\nbaseurl=https://packages.centreon.com/rpm-plugins/${{ matrix.distrib }}/stable/x86_64\nenabled=1\ngpgcheck=1\ngpgkey=https://yum-gpg.centreon.com/RPM-GPG-KEY-CES\n[centreon-plugins-stable-noarch]\nname=centreon plugins stable noarch\nbaseurl=https://packages.centreon.com/rpm-plugins/${{ matrix.distrib }}/stable/noarch\nenabled=1\ngpgcheck=1\ngpgkey=https://yum-gpg.centreon.com/RPM-GPG-KEY-CES\n' >> /etc/yum.repos.d/centreon-plugins.repo
         shell: bash
       - if: ${{ matrix.package_extension == 'deb' }}
         name: Install zstd, perl and Centreon repositories
@@ -582,11 +586,11 @@ jobs:
           apt-get update
           apt-get install -y zstd perl wget gpg apt-utils
           # Add Centreon plugins repositories
-          if [ "${{ matrix.distrib }}" == "jammy" ]; then
-            echo "deb https://packages.centreon.com/ubuntu-plugins-stable/ ${{ matrix.distrib }} main" | tee /etc/apt/sources.list.d/centreon-plugins.list
-          else
-            echo "deb https://packages.centreon.com/apt-plugins-stable/ ${{ matrix.distrib }} main" | tee /etc/apt/sources.list.d/centreon-plugins.list
-          fi
+          # if [ "${{ matrix.distrib }}" == "jammy" ]; then
+          #   echo "deb https://packages.centreon.com/ubuntu-plugins-stable/ ${{ matrix.distrib }} main" | tee /etc/apt/sources.list.d/centreon-plugins.list
+          # else
+          #   echo "deb https://packages.centreon.com/apt-plugins-stable/ ${{ matrix.distrib }} main" | tee /etc/apt/sources.list.d/centreon-plugins.list
+          # fi
           wget -O- https://apt-key.centreon.com | gpg --dearmor | tee /etc/apt/trusted.gpg.d/centreon.gpg > /dev/null 2>&1
           apt-get update
         shell: bash
@@ -596,54 +600,73 @@ jobs:
           path: ./*.${{ matrix.package_extension }}
           key: ${{ github.sha }}-${{ github.run_id }}-${{ matrix.package_extension }}-${{ matrix.distrib }}
           fail-on-cache-miss: true
-      - name: Install packages
+      - if: ${{ matrix.package_extension == 'rpm' }}
+        name: Install packages
         run: |
           error_log="install_error_${{ matrix.distrib }}_${{ matrix.arch }}.log"
           for package in ./*.${{ matrix.package_extension }}; do
-            # If a debian package name ends with amd64 or arm64, we only install it if the tested architecture is the same, otherwise we skip it
+            echo "Installing package: $package"
+            # List dependencies, and remove version and comparison operators
+            dependencies=$(rpm -qpR $package | sed 's/ [0-9.-]*\(\s\|$\)/ /g' | sed 's/ [<>!=]*\(\s\|$\)/ /g')
+            for dependency in $dependencies; do
+              # Skip non-perl dependencies
+              if [[ $dependency != perl* ]]; then
+                continue
+              else
+                echo "Check dependency: $dependency"
+                # Update the dependency name to match the package name
+                dependency=$(echo $dependency | sed 's/(/-/g' | sed 's/)//g' | sed 's/::/-/g')
+              fi
+              # If the dependency has been built in the same workflow, install it
+              if [[ -n $(find . -maxdepth 1 -regex "\.\/$dependency-[0-9v].*\.${{ matrix.package_extension }}") ]]; then
+                echo "Installing dependency: $dependency"
+                error_output=$(dnf install -y ./$dependency*.rpm 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of the dependency $dependency" >> $error_log; true; }
+              fi
+            done
+            # Install package, then uninstall it with all his dependencies
+            echo "Package installation..."
+            error_output=$(dnf install -y $package 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of the package $package" >> $error_log; true; }
+            echo "Package installation done."
+            echo "Package uninstallation..."
+            error_output=$(dnf autoremove -y $(echo $package | sed 's/_[0-9].*\.rpm//' | sed 's/.\///') 2>&1) || { echo "$error_output" >> $error_log; echo "Error during autoremove of the package $package" >> $error_log; true; }
+            echo "Package uninstallation done."
+          done
+          # If the file error_log exists and is not empty, the workflow is in error
+          if [[ -s $error_log ]]; then
+              cat $error_log
+              exit 1
+          fi
+        shell: bash
+      - if: ${{ matrix.package_extension == 'deb' }}
+        name: Install packages
+        run: |
+          error_log="install_error_${{ matrix.distrib }}_${{ matrix.arch }}.log"
+          for package in ./*.${{ matrix.package_extension }}; do
+            # If the debian package name ends with amd64 or arm64, we only install it if the tested architecture is the same, otherwise we skip it
             if [[ ${{ matrix.package_extension }} == 'deb' && ($package == *amd64.deb && ${{ matrix.arch }} != "amd64" || $package == *arm64.deb && ${{ matrix.arch }} != "arm64") ]]; then
               continue
             fi
             echo "Installing package: $package"
             # List dependencies
-            if [ "${{ matrix.package_extension }}" == "rpm" ]; then
-              dependencies=$(rpm -qpR $package)
-            else
-              dependencies=$(dpkg-deb -I $package | grep Depends | sed 's/Depends: //')
-            fi
+            dependencies=$(dpkg-deb -I $package | grep Depends | sed 's/Depends: //' | sed 's/,//g')
             for dependency in $dependencies; do
               # Skip non-perl dependencies
-              if [ "${{ matrix.package_extension }}" == "rpm" ]; then
-                if [[ $dependency != perl* ]]; then
+              if [[ $dependency != lib*-perl ]]; then
                   continue
-                else
-                  echo "Check dependency: $dependency"
-                  # Update the dependency name to match the package name
-                  dependency=$(echo $dependency | sed 's/(/-/g' | sed 's/)//g' | sed 's/::/-/g')
-                fi
-              elif [[ "${{ matrix.package_extension }}" == "deb" && $dependency != lib*-perl ]]; then
-                  continue
-              else
-                echo "Check dependency: $dependency"
               fi
               # If the dependency has been built in the same workflow, install it
-              if [[ -f ./$dependency*.${{ matrix.package_extension }} ]]; then
+              if [[ -n $(find . -maxdepth 1 -regex "\.\/lib.*-perl[-_][0-9].*all\.${{ matrix.package_extension }}" -o -regex "\.\/lib.*-perl[-_][0-9].*${{ matrix.arch }}\.${{ matrix.package_extension }}") ]]; then
                 echo "Installing dependency: $dependency"
-                if [ "${{ matrix.package_extension }}" == "rpm" ]; then
-                  error_output=$(dnf install -y ./$dependency*.rpm 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of the dependency $dependency" >> $error_log; true; }
-                else
-                  error_output=$(apt-get install -y ./$dependency*.deb 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of the dependency $dependency" >> $error_log; true; }
-                fi
+                error_output=$(apt-get install -y ./$dependency*.deb 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of the dependency $dependency" >> $error_log; true; }
               fi
             done
             # Install package, then uninstall it with all his dependencies
-            if [ "${{ matrix.package_extension }}" == "rpm" ]; then
-              error_output=$(dnf install -y $package 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of the package $package" >> $error_log; true; }
-              error_output=$(dnf autoremove -y $(echo $package | sed 's/_[0-9].*\.rpm//' | sed 's/.\///') 2>&1) || { echo "$error_output" >> $error_log; echo "Error during autoremove of the package $package" >> $error_log; true; }
-            else
-              error_output=$(apt-get install -y $package 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of the package $package" >> $error_log; true; }
-              error_output=$(apt-get autoremove -y --purge $(echo $package | sed 's/_[0-9].*\.deb//' | sed 's/.\///') 2>&1) || { echo "$error_output" >> $error_log; echo "Error during autoremove of the package $package" >> $error_log; true; }
-            fi
+            echo "Package installation..."
+            error_output=$(apt-get install -y $package 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of the package $package" >> $error_log; true; }
+            echo "Package installation done."
+            echo "Package uninstallation..."
+            error_output=$(apt-get autoremove -y --purge $(echo $package | sed 's/_[0-9].*\.deb//' | sed 's/.\///') 2>&1) || { echo "$error_output" >> $error_log; echo "Error during autoremove of the package $package" >> $error_log; true; }
+            echo "Package uninstallation done."
           done
           # If the file error_log exists and is not empty, the workflow is in error
           if [[ -s $error_log ]]; then
