Fix check package existence for el

diff --git a/.github/workflows/perl-new-cpan-libraries.yml b/.github/workflows/perl-new-cpan-libraries.yml
--- a/.github/workflows/perl-new-cpan-libraries.yml
+++ b/.github/workflows/perl-new-cpan-libraries.yml
@@ -63,14 +63,35 @@ jobs:
         uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
 
       - if: ${{ contains(matrix.build_distribs, matrix.distrib) }}
+        name: Get package infos
+        id: package-infos
+        run: |
+          cpan_info=$(cpanm --info ${{ matrix.name }})
+          if [ -z "${{ matrix.version }}" ]; then
+            CPAN_PACKAGE_VERSION=$(echo $cpan_info | sed 's/\.tar\.gz$//' | sed 's/.*\-//' | sed 's/v//')
+            if [[ ! $CPAN_PACKAGE_VERSION =~ ^[0-9]+\.[0-9]+ ]]; then
+              echo "::error::Invalid version number: ${CPAN_PACKAGE_VERSION}"
+              exit 1
+            fi
+            PACKAGE_VERSION="${CPAN_PACKAGE_VERSION}"
+          else
+            PACKAGE_VERSION="${{ matrix.version }}"
+          fi
+          echo "package_version=$(echo $PACKAGE_VERSION)" >> $GITHUB_OUTPUT
+          CPAN_PACKAGE_NAME=$(echo $cpan_info | sed 's/.*\///g' | sed 's/-[0-9\.]*\.tar\.gz//g')
+          PACKAGE_NAME="perl-$CPAN_PACKAGE_NAME"
+          echo "package_name=$(echo $PACKAGE_NAME)" >> $GITHUB_OUTPUT
+        shell: bash
+
+      - if: ${{ contains(matrix.build_distribs, matrix.distrib) }}
         name: Check if package already exists
         id: check-package-existence
         run: |
-          package_info=$(dnf provides 'perl(${{ matrix.name }})' 2>&1 | tr '[:upper:]' '[:lower:]' || true)
+          package_info=$(dnf provides 'perl(${{ matrix.name }})' 2>&1 || true)
           do_not_build="false"
-          if [[ ! $package_info =~ "no matches found" ]]; then
+          if [[ ! $package_info =~ "No Matches found" ]]; then
             package_version=$(echo $package_info | grep -oP 'perl\(${{ matrix.name }}\) = \K[0-9]+\.[0-9]+')
-            if [[ -z "${{ matrix.version }}" || "$package_version" == "${{ matrix.version }}" ]]; then
+            if [[ "$package_version" == "${{ steps.package-infos.outputs.package_version }}" ]]; then
               echo "::warning::Package ${{ matrix.name }} already exists in the official ${{ matrix.distrib }} repository with the same version."
               do_not_build="true"
             else
@@ -83,17 +104,7 @@ jobs:
 
       - if: ${{ steps.check-package-existence.outputs.do_not_build == 'false' && contains(matrix.build_distribs, matrix.distrib) && matrix.spec_file == '' }}
         run: |
-          cpan_info=$(cpanm --info ${{ matrix.name }})
-          if [ -z "${{ matrix.version }}" ]; then
-            CPAN_PACKAGE_VERSION=$(echo $cpan_info | sed 's/\.tar\.gz$//' | sed 's/.*\-//' | sed 's/v//')
-            if [[ ! $CPAN_PACKAGE_VERSION =~ ^[0-9]+\.[0-9]+ ]]; then
-              echo "::error::Invalid version number: ${CPAN_PACKAGE_VERSION}"
-              exit 1
-            fi
-            PACKAGE_VERSION=" -v ${CPAN_PACKAGE_VERSION}"
-          else
-            PACKAGE_VERSION=" -v ${{ matrix.version }}"
-          fi
+          PACKAGE_VERSION=" -v ${{ steps.package-infos.outputs.package_version }}"
 
           if [ -z "${{ matrix.rpm_dependencies }}" ]; then
             PACKAGE_DEPENDENCIES=""
