update workflow + fix dependencies installation

diff --git a/.github/workflows/perl-cpan-libraries.yml b/.github/workflows/perl-cpan-libraries.yml
--- a/.github/workflows/perl-cpan-libraries.yml
+++ b/.github/workflows/perl-cpan-libraries.yml
@@ -604,13 +604,13 @@ jobs:
             for dependency in $dependencies; do
               # If the dependency has been built in the same workflow, install it
               if [ -f $dependency*.rpm ]; then
-                error_output=$(dnf install -y $dependency*.rpm 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of $dependency" >> $error_log; true; }
+                error_output=$(dnf install -y $dependency*.rpm 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of the dependency $dependency" >> $error_log; true; }
               fi
             done
             # Install package
-            error_output=$(dnf install -y $package 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of $package" >> $error_log; true; }
+            error_output=$(dnf install -y $package 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of the package $package" >> $error_log; true; }
             # Uninstall package with all his dependencies
-            error_output=$(dnf autoremove -y $(echo $package | sed 's/_[0-9].*\.rpm//' | sed 's/.\///') 2>&1) || { echo "$error_output" >> $error_log; echo "Error during autoremove of $package" >> $error_log; true; }
+            error_output=$(dnf autoremove -y $(echo $package | sed 's/_[0-9].*\.rpm//' | sed 's/.\///') 2>&1) || { echo "$error_output" >> $error_log; echo "Error during autoremove of the package $package" >> $error_log; true; }
           done
           # Si le fichier error_log existe et n'est pas vide, le workflow est en erreur
           if [ -s $error_log ]; then
@@ -623,19 +623,22 @@ jobs:
         run: |
           error_log="install_error_${{ matrix.distrib }}_${{ matrix.arch }}.log"
           for package in ./*.deb; do
+            # If the package name ends with amd64 or arm64, we only install it if the tested architecture is the same, otherwise we skip it
+            if [[ $package == *amd64.deb && ${{ matrix.arch }} != "amd64" ]] || [[ $package == *arm64.deb && ${{ matrix.arch }} != "arm64" ]]; then
+              continue
+            fi
             # List dependencies
             dependencies=$(dpkg-deb -I $package | grep Depends | sed 's/Depends: //')
             for dependency in $dependencies; do
                 # If the dependency has been built in the same workflow, install it
                 if [ -f $dependency*.deb ]; then
-                  error_output=$(apt-get install -y $dependency*.deb 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of $dependency" >> $error_log; true; }
+                  error_output=$(apt-get install -y $dependency*.deb 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of the dependency $dependency" >> $error_log; true; }
                 fi
             done
             # Install package
-            error_output=$(apt-get install -y $package 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of $package" >> $error_log; true; }
+            error_output=$(apt-get install -y $package 2>&1) || { echo "$error_output" >> $error_log; echo "Error during installation of the package $package" >> $error_log; true; }
             # Uninstall package with all his dependencies
-            # Package name is the name of the file less the version and the .deb extension, and without the "./" at the beginning
-            error_output=$(apt-get autoremove -y --purge $(echo $package | sed 's/_[0-9].*\.deb//' | sed 's/.\///') 2>&1) || { echo "$error_output" >> $error_log; echo "Error during autoremove of $package" >> $error_log; true; }
+            error_output=$(apt-get autoremove -y --purge $(echo $package | sed 's/_[0-9].*\.deb//' | sed 's/.\///') 2>&1) || { echo "$error_output" >> $error_log; echo "Error during autoremove of the package $package" >> $error_log; true; }
           done
           # Si le fichier error_log existe et n'est pas vide, le workflow est en erreur
           if [ -s $error_log ]; then
